### ISSUE TITLE
Output box does not correctly update

### ISSUE THREAD

**Issue by heuristicus** [ori-drs/procman_ros#27]
When running icp odometry I noticed that the box which shows the terminal output does not expand to contain the text. The output flashes on the screen very briefly but the message is not visible in the box and it does not scroll. Scrolling up and then back down makes all the messages that were missed visible again.

https://user-images.githubusercontent.com/636456/119978295-5f110680-bfb1-11eb-9a02-5c20483e1799.mp4

The file which controls this display is https://github.com/ori-drs/procman_ros/blob/master/python/src/procman_ros/sheriff_gtk/command_console.py.

**Comment by mauricefallon** [comment]
I've been struggling with this ... if you could fix it that would be fantastic

**Comment by heuristicus** [comment]
@mauricefallon I'm trying to find a consistent way to reproduce this - do you have a specific node this happens with a lot when using spot postprocessing for example?

**Comment by heuristicus** [comment]
I ran the echo test again, and I'm pretty sure this issue happens when we have to both add to and delete from the text buffer at the same time. When the buffer is not yet full, the speed of the seq values is pretty much as you would expect. As soon as the buffer reaches the specified maximum characters, there is an immediate slowdown in the seq values and the printing appears incorrect. Need to work out how to properly update the textview in this case.

**Comment by heuristicus** [comment]
I tried these changes but the result is still the same.

```diff
diff --git a/python/src/procman_ros/sheriff_gtk/command_console.py b/python/src/procman_ros/sheriff_gtk/command_console.py
index 32a3bb4..031802b 100644
--- a/python/src/procman_ros/sheriff_gtk/command_console.py
+++ b/python/src/procman_ros/sheriff_gtk/command_console.py
@@ -50,7 +50,7 @@ class SheriffCommandConsole(Gtk.ScrolledWindow, SheriffListener):
     def __init__(self, _sheriff):
         super(SheriffCommandConsole, self).__init__()
 
-        self.stdout_maxlines = 2000
+        self.stdout_maxlines = 250
         self.max_kb_per_sec = 0
         self.max_chars_per_2500_ms = 0
 
@@ -186,6 +186,16 @@ class SheriffCommandConsole(Gtk.ScrolledWindow, SheriffListener):
 
         # interpret text as ANSI escape sequences?  Try to format colors...
         tag = self.text_tags["normal"]
+        lines_to_be_added = text.count('\n')
+        print("lines to add {}".format(lines_to_be_added))
+
+        # toss out old text if the muffer is getting too big
+        num_lines = tb.get_line_count()
+        if num_lines + lines_to_be_added > self.stdout_maxlines:
+            start_iter = tb.get_start_iter()
+            chop_iter = tb.get_iter_at_line(num_lines - self.stdout_maxlines + lines_to_be_added)
+            tb.delete(start_iter, chop_iter)
+
         for segnum, seg in enumerate(text.split("\x1b[")):
             if not seg:
                 continue
@@ -197,13 +207,6 @@ class SheriffCommandConsole(Gtk.ScrolledWindow, SheriffListener):
             end_iter = tb.get_end_iter()
             tb.insert_with_tags(end_iter, seg, tag)
 
-        # toss out old text if the muffer is getting too big
-        num_lines = tb.get_line_count()
-        if num_lines > self.stdout_maxlines:
-            start_iter = tb.get_start_iter()
-            chop_iter = tb.get_iter_at_line(num_lines - self.stdout_maxlines)
-            tb.delete(start_iter, chop_iter)
-
     # Sheriff event handlers
     def _gtk_on_sheriff_command_added(self, deputy, command):
         extradata = CommandExtraData(self.sheriff_tb.get_tag_table())
```

**Comment by mauricefallon** [comment]
> @mauricefallon I'm trying to find a consistent way to reproduce this - do you have a specific node this happens with a lot when using spot postprocessing for example?

I have this problem regularly with VILENS-SLAM and VILENS. It doesnt have to be high frequency (like you showed)

**Comment by heuristicus** [comment]
The problem was doing something that causes a change of the displayed UI without using `GLib.idle_add`. Really need to better understand how to see which parts of code need to be run by using that function. Something about how if something isn't in the main thread it always has to be done with the idle add.
