### ISSUE TITLE
unable to run headless scripts

### ISSUE THREAD

**Issue by mauricefallon** [ori-drs/procman_ros#31]
The feature which can allow procman to run a script headless is not working. (enabled by -n below)
There seems to be some left over lcm code within it - see error message below.

Running the script automatically as shown below does work (without the -n)

My use case it running VILENS and VILENS-SLAM on a log and automatically saving the output map to file.

I imagine it wouldnt be complicated to fix. Could you have a look?

```
rosrun procman_ros sheriff -l frontier.pmd --script offline_vilens_and_slam_rotated_ouster -n
[rosrun] Couldn't find executable named procman_ros_deputy below /opt/ros/noetic/share/procman_ros
Running script offline_vilens_and_slam_rotated_ouster
Sheriff terminating..
Terminating local deputy..
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/procman_ros/sheriff", line 3, in <module>
    procman_ros.sheriff_gtk.sheriff_gtk.main()
  File "/opt/ros/noetic/lib/python3/dist-packages/procman_ros/sheriff_gtk/sheriff_gtk.py", line 821, in main
    SheriffHeadless(
  File "/opt/ros/noetic/lib/python3/dist-packages/procman_ros/sheriff_cli.py", line 102, in run
    self.lcm_obj.handle_timeout(200)
AttributeError: 'SheriffHeadless' object has no attribute 'lcm_obj'
```

**Comment by heuristicus** [comment]
It looks like you're on an older version of procman, if you get the latest version from https://drs-packages.robots.ox.ac.uk/pool/main/r/ros-noetic-procman-ros this error should go away.

I've done a bit of testing with the current code and I don't think the script execution functionality in headless mode works. At least, I was unable to run a script with a wait in it.
