### ISSUE TITLE
CPU and process memory data comes from the rosrun or roslaunch process and does not reflect usage of nodes

### ISSUE THREAD

**Issue by heuristicus** [ori-drs/procman_ros#6]
The memory usage reported by the deputy to the sheriff is suspiciously uniform and does not seem to match the data from process monitor or top.

![Screenshot from 2020-06-22 13-43-16](https://user-images.githubusercontent.com/636456/85288848-573a0f80-b48e-11ea-9155-57c6cd5d7298.png)

Process information is read at https://github.com/ori-drs/procman_ros/blob/master/src/procman/procinfo_linux.cpp#L133-L175

It looks at files of the form /proc/[pid]/stat. Documentation for that is at https://man7.org/linux/man-pages/man5/proc.5.html. It seems that the consistent memory usage may be because it is looking at the stats for the roslaunch/rosrun process rather than the process itself?

**Comment by mcamurri** [comment]
In my experience, if you a ROS node from a launch file, the process is wrapped by ROS executable, so it is possible the memory tracked is the one of the ROS process. I don't know if a ROS node by itself is also wrapped. 

Anyways, the memory feature is not as important as the total load of a machine, but it is useful to have.

Have you checked running a test program with known used memory (e.g. a program that allocates a fixed sized array) with  both the LCM and ROS version and see if they show the same number?

There should be a way to get the memory consumption also programmatically: https://stackoverflow.com/questions/5120861/how-to-measure-memory-usage-from-inside-a-c-program

**Comment by heuristicus** [comment]
It's not just the memory - since the CPU is also based off the roslaunch or rosrun process, it's always 0 or almost nothing for all the processes we start.

I've not run a test program, but it's not an LCM/ROS version thing, it's just the processes that the system starts. If you start a process which actually runs in the originally spawned process, then your cpu/memory usage will be accurate (I tried it with `top`)

I think the fix is probably to get the memory/cpu usage of the entire process group rather than only the process that procman itself starts, which will catch the rosrun/launch child processes.

**Comment by mcamurri** [comment]
If this is a bug from procman in general, then it should be also reported upstream. It shouldn't be hard to fix it, this discussion seems relavant: https://stackoverflow.com/questions/1420426/how-to-calculate-the-cpu-usage-of-a-process-by-pid-in-linux-from-c

**Comment by heuristicus** [comment]
The functions which gather process/system info are at https://github.com/ori-drs/procman_ros/blob/master/src/procman/procinfo_linux.cpp#L133-L247, and are called from https://github.com/ori-drs/procman_ros/blob/master/src/procman_ros/procman_deputy.cpp#L424-L476, which also populates the structs that are later used to fill the messages sent to the sheriff.

**Comment by heuristicus** [comment]
I checked my assumption about rosrun also not having correct memory/cpu usage - it turns out that the processes started by deputy with rosrun have correct memory and cpu usage. I used this tiny program to check memory usage:

```
#!/usr/bin/env python

import time

my_list = []

while True:
    my_list.extend([0]*1000000)
    time.sleep(5)
```

**Comment by heuristicus** [comment]
To fix, should be sufficient to use `GetDescendants` from procinfo_linux in `UpdateCpuTimes` and loop over the pid of the command run by deputy, plus its descendants.
